# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /tmp

COPY . ./
RUN dotnet restore ./Server/Server.csproj
RUN dotnet publish ./Server/Server.csproj -c Release --self-contained false -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
ENV ASPNETCORE_URLS=http://*:7001
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Server.dll"]