# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build-template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      merge:
        required: true
        type: boolean
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

jobs:
  build:
    name: Run dotnet build for env ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      env:
        branchname: ${GITHUB_REF#refs/heads/}
        commit1: ${GITHUB_SHA}
        commit2: ${GITHUB_SHA::7}
        commit3: $(git rev-parse --short "$GITHUB_SHA")
        commit4: ${{ github.event.pull_request.head.sha }}
      run: |
        echo "The GitHub Action Secret will be masked: ${{env.commit1}}  / ${{env.commit2}} / ${{env.commit3}}  /  ${{ secrets.ACR_USERNAME }} / ${{ secrets.ACR_PASSWORD }} / ! ${{ vars.ACRENDPOINT }} !!"
        echo "/ ${{env.commit4}} / ${{env.branchname}}"
    - name: Test again
      if: ${{ inputs.merge == true }}
      run: dotnet test --no-build --verbosity normal

  docker1:
    name: Run docker1 build and push for env ${{ inputs.environment }}
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Prepare
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        echo ::set-output name=tag::${TAG}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to image repository
      if: ${{ inputs.merge == true }}
      uses: docker/login-action@v2
      with:
        registry: ${{ vars.ACRENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Docker Build and push
      env:
        branchname: ${GITHUB_REF#refs/heads/}
        commit1: ${GITHUB_SHA}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.Server
        push: ${{ inputs.merge == true }}
        tags: ${{ vars.ACRENDPOINT }}/${{ vars.REPONAME }}:${{ steps.prep.outputs.tag }}
  
  docker2:
    name: Run docker2 build and push for env ${{ inputs.environment }}
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Prepare
      id: prep
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        echo ::set-output name=tag::${TAG}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to image repository
      if: ${{ inputs.merge == true }}
      uses: docker/login-action@v2
      with:
        registry: ${{ vars.ACRENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Docker Build and push
      env:
        branchname: ${GITHUB_REF#refs/heads/}
        commit1: ${GITHUB_SHA}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.Server
        push: ${{ inputs.merge == true }}
        tags: ${{ vars.ACRENDPOINT }}/${{ vars.REPONAME }}:${{ steps.prep.outputs.tag }}
    