# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: main-pull-request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      environment: prod
      merge: false
    secrets:
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
