# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: main-branch

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      environment: prod
      merge: true
      imageversion: ${GITHUB_SHA::7}
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
